package:
  name: mmcif
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - cmake
  - bison
  - flex
  - {{ compiler('c') }}
  - {{ compiler('cxx') }}
  host:
  - python
  - pip
  - setuptools >=61.0
  run:
  - python
  - requests >=2.25
  - msgpack-python
about:
  home: https://mmcif.wwpdb.org
  license: Apache-2.0
  summary: 'Forked packaging to enable conda installation of mmCIF Core Access Library'
  description: 'This package is built from a fork of https://github.com/rcsb/py-mmcif. The fork exists solely to enable installation via conda, since no conda packages are available for this library. The uibcdf channel is used as our distribution channel to address this gap.'
  dev_url: https://github.com/uibcdf/py-mmcif
